import React, { useState, useEffect, useMemo } from 'react';
import {
  Bot,
  Copy,
  Check,
  Download,
  Plus,
  Trash2,
  AlertCircle,
  Sparkles,
  Sliders,
  ShieldAlert,
  Globe,
  RefreshCw,
  Layers
} from 'lucide-react';
import { toast } from '../../utils/toast';

interface BotRule {
  id: string;
  name: string;
  useragent: string;
  category: 'search' | 'ai' | 'social';
  allowed: boolean;
}

type PresetId = 'standard' | 'block-ai' | 'staging' | 'ecommerce';

export default function RobotsGenerator() {
  const [bots, setBots] = useState<BotRule[]>([
    { id: 'all', name: 'All Web Crawlers (*)', useragent: '*', category: 'search', allowed: true },
    { id: 'google', name: 'Googlebot (Search)', useragent: 'Googlebot', category: 'search', allowed: true },
    { id: 'bing', name: 'Bingbot (Bing & Copilot)', useragent: 'Bingbot', category: 'search', allowed: true },
    { id: 'duck', name: 'DuckDuckBot (DuckDuckGo)', useragent: 'DuckDuckBot', category: 'search', allowed: true },
    { id: 'openai', name: 'GPTBot (OpenAI Web)', useragent: 'GPTBot', category: 'ai', allowed: false },
    { id: 'chatgpt', name: 'ChatGPT-User (Browsing)', useragent: 'ChatGPT-User', category: 'ai', allowed: false },
    { id: 'claude', name: 'ClaudeBot / Anthropic', useragent: 'ClaudeBot', category: 'ai', allowed: false },
    { id: 'googleai', name: 'Google-Extended (Gemini)', useragent: 'Google-Extended', category: 'ai', allowed: false },
    { id: 'ccbot', name: 'CCBot (Common Crawl)', useragent: 'CCBot', category: 'ai', allowed: false },
    { id: 'bytespider', name: 'Bytespider (ByteDance)', useragent: 'Bytespider', category: 'ai', allowed: false },
  ]);

  const [sitemapUrl, setSitemapUrl] = useState('https://smarttoolhub.net/sitemap.xml');
  const [crawlDelay, setCrawlDelay] = useState<number>(0);
  const [hostUrl, setHostUrl] = useState('');
  const [customPaths, setCustomPaths] = useState<{ path: string; type: 'disallow' | 'allow' }[]>([
    { path: '/admin/', type: 'disallow' },
    { path: '/api/', type: 'disallow' },
    { path: '/private/', type: 'disallow' },
  ]);
  const [newPath, setNewPath] = useState('');
  const [newPathType, setNewPathType] = useState<'disallow' | 'allow'>('disallow');
  const [copied, setCopied] = useState(false);

  const applyPreset = (preset: PresetId) => {
    if (preset === 'standard') {
      setBots((prev) =>
        prev.map((b) => ({
          ...b,
          allowed: b.category === 'search'
        }))
      );
      setCustomPaths([
        { path: '/admin/', type: 'disallow' },
        { path: '/api/', type: 'disallow' },
      ]);
      toast.info('Applied Standard SEO profile.');
    } else if (preset === 'block-ai') {
      setBots((prev) =>
        prev.map((b) => ({
          ...b,
          allowed: b.category !== 'ai'
        }))
      );
      toast.info('All AI & LLM scrapers blocked.');
    } else if (preset === 'staging') {
      setBots((prev) =>
        prev.map((b) => ({
          ...b,
          allowed: false
        }))
      );
      setCustomPaths([{ path: '/', type: 'disallow' }]);
      toast.info('Applied Private Staging profile (disallow all).');
    } else if (preset === 'ecommerce') {
      setBots((prev) =>
        prev.map((b) => ({
          ...b,
          allowed: b.category === 'search'
        }))
      );
      setCustomPaths([
        { path: '/cart/', type: 'disallow' },
        { path: '/checkout/', type: 'disallow' },
        { path: '/account/', type: 'disallow' },
        { path: '/search?*', type: 'disallow' },
      ]);
      toast.info('Applied E-Commerce optimized paths.');
    }
  };

  // Compile robots.txt rules dynamically
  const robotsTxt = useMemo(() => {
    let output = `# ========================================================\n`;
    output += `# Robots.txt Directives\n`;
    output += `# Generated by SmartToolHub SEO Studio on ${new Date().toISOString().split('T')[0]}\n`;
    output += `# ========================================================\n\n`;

    // 1. Specific blocked bots first
    const blockedBots = bots.filter((b) => b.useragent !== '*' && !b.allowed);
    if (blockedBots.length > 0) {
      output += `# Blocked AI / Scraping Bots\n`;
      blockedBots.forEach((bot) => {
        output += `User-agent: ${bot.useragent}\nDisallow: /\n\n`;
      });
    }

    // 2. Specific allowed custom bots
    const allowedSpecificBots = bots.filter((b) => b.useragent !== '*' && b.allowed);
    if (allowedSpecificBots.length > 0) {
      output += `# Explicitly Allowed Search Crawlers\n`;
      allowedSpecificBots.forEach((bot) => {
        output += `User-agent: ${bot.useragent}\nDisallow:\n\n`;
      });
    }

    // 3. Default wildcard rules
    const defaultBot = bots.find((b) => b.useragent === '*');
    output += `# Default Crawl Rules\n`;
    output += `User-agent: *\n`;

    if (defaultBot && !defaultBot.allowed) {
      output += `Disallow: /\n`;
    } else {
      if (customPaths.length > 0) {
        customPaths.forEach((cp) => {
          const prefix = cp.type === 'disallow' ? 'Disallow' : 'Allow';
          output += `${prefix}: ${cp.path}\n`;
        });
      } else {
        output += `Disallow:\n`;
      }
    }

    if (crawlDelay > 0) {
      output += `Crawl-delay: ${crawlDelay}\n`;
    }

    output += `\n`;

    // 4. Sitemap & Host
    if (sitemapUrl.trim()) {
      output += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    if (hostUrl.trim()) {
      output += `Host: ${hostUrl.trim()}\n`;
    }

    return output;
  }, [bots, sitemapUrl, hostUrl, crawlDelay, customPaths]);

  const handleToggleBot = (id: string) => {
    setBots((prev) =>
      prev.map((bot) => (bot.id === id ? { ...bot, allowed: !bot.allowed } : bot))
    );
  };

  const handleAddPath = (e: React.FormEvent) => {
    e.preventDefault();
    const cleanPath = newPath.trim();
    if (!cleanPath) return;

    let formattedPath = cleanPath;
    if (!formattedPath.startsWith('/') && !formattedPath.startsWith('*')) {
      formattedPath = '/' + formattedPath;
    }

    setCustomPaths((prev) => [...prev, { path: formattedPath, type: newPathType }]);
    setNewPath('');
  };

  const handleRemovePath = (idx: number) => {
    setCustomPaths((prev) => prev.filter((_, i) => i !== idx));
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(robotsTxt);
      setCopied(true);
      toast.success('robots.txt copied to clipboard!', 'Copied');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy.');
    }
  };

  const handleDownload = () => {
    const blob = new Blob([robotsTxt], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'robots.txt';
    link.click();
    URL.revokeObjectURL(url);
    toast.success('Downloaded robots.txt file.', 'File Saved');
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Header Banner */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-6 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 rounded-full text-xs font-bold uppercase tracking-wider mb-2">
              <Bot size={13} /> SEO & Indexing Directives
            </div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white">
              Robots.txt Generator & Validator
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Configure search engine crawling rules, block unauthorized AI scrapers (OpenAI, Gemini, Anthropic), and manage sitemaps.
            </p>
          </div>

          <div className="flex items-center gap-2 self-start sm:self-center">
            <button
              onClick={handleCopy}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition-all shadow-xs flex items-center gap-1.5 cursor-pointer"
            >
              {copied ? <Check size={14} className="text-white" /> : <Copy size={14} />}
              <span>{copied ? 'Copied!' : 'Copy Schema'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3.5 py-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 hover:bg-slate-800 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer"
            >
              <Download size={14} />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Quick Presets */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-4">
          <button
            onClick={() => applyPreset('standard')}
            className="p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50 dark:hover:bg-indigo-950/30 text-left text-xs font-bold text-slate-700 dark:text-slate-300 transition-all cursor-pointer"
          >
            🛡️ Standard Search Ready
          </button>
          <button
            onClick={() => applyPreset('block-ai')}
            className="p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50 dark:hover:bg-indigo-950/30 text-left text-xs font-bold text-slate-700 dark:text-slate-300 transition-all cursor-pointer"
          >
            🚫 Block All AI Scrapers
          </button>
          <button
            onClick={() => applyPreset('ecommerce')}
            className="p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50 dark:hover:bg-indigo-950/30 text-left text-xs font-bold text-slate-700 dark:text-slate-300 transition-all cursor-pointer"
          >
            🛒 E-Commerce Optimized
          </button>
          <button
            onClick={() => applyPreset('staging')}
            className="p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/40 hover:bg-indigo-50 dark:hover:bg-indigo-950/30 text-left text-xs font-bold text-slate-700 dark:text-slate-300 transition-all cursor-pointer"
          >
            🔒 Private Dev / Staging
          </button>
        </div>
      </div>

      {/* Main Studio Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Settings */}
        <div className="lg:col-span-6 space-y-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-xs space-y-4">
            <span className="text-xs font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider flex items-center gap-1.5 border-b border-slate-100 dark:border-slate-800 pb-3">
              <Sliders size={14} className="text-indigo-500" /> Crawl Endpoints & Sitemaps
            </span>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Sitemap XML Link
                </label>
                <input
                  type="url"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  placeholder="https://example.com/sitemap.xml"
                  className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs text-slate-900 dark:text-white font-mono focus:ring-1 focus:ring-indigo-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
                  Crawl Delay (Seconds)
                </label>
                <input
                  type="number"
                  min={0}
                  max={60}
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(parseInt(e.target.value) || 0)}
                  className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs text-slate-900 dark:text-white font-mono focus:ring-1 focus:ring-indigo-500 outline-none"
                />
              </div>
            </div>

            {/* Bots Table */}
            <div className="space-y-2 pt-2">
              <span className="text-xs font-bold text-slate-700 dark:text-slate-300 block">
                Crawler Access Matrix
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-56 overflow-y-auto pr-1">
                {bots.map((bot) => (
                  <div
                    key={bot.id}
                    className="flex items-center justify-between p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/40 text-xs"
                  >
                    <div>
                      <div className="font-bold text-slate-800 dark:text-slate-200">{bot.name}</div>
                      <div className="text-[10px] font-mono text-slate-400">{bot.useragent}</div>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleToggleBot(bot.id)}
                      className={`px-2.5 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${
                        bot.allowed
                          ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'
                          : 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20'
                      }`}
                    >
                      {bot.allowed ? 'Allow' : 'Block'}
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Custom Paths */}
            <div className="space-y-3 pt-3 border-t border-slate-100 dark:border-slate-800">
              <span className="text-xs font-bold text-slate-700 dark:text-slate-300 block">
                Path Directives ({customPaths.length})
              </span>

              <div className="space-y-1.5 max-h-36 overflow-y-auto">
                {customPaths.map((cp, idx) => (
                  <div
                    key={idx}
                    className="flex items-center justify-between px-3 py-1.5 bg-slate-50 dark:bg-slate-800 rounded-lg text-xs border border-slate-200 dark:border-slate-700"
                  >
                    <div className="flex items-center gap-2">
                      <span
                        className={`px-1.5 py-0.5 rounded text-[9px] font-bold uppercase ${
                          cp.type === 'disallow'
                            ? 'bg-rose-500/10 text-rose-600'
                            : 'bg-emerald-500/10 text-emerald-600'
                        }`}
                      >
                        {cp.type}
                      </span>
                      <span className="font-mono text-slate-700 dark:text-slate-300">{cp.path}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleRemovePath(idx)}
                      className="text-slate-400 hover:text-rose-500 cursor-pointer"
                    >
                      <Trash2 size={13} />
                    </button>
                  </div>
                ))}
              </div>

              <form onSubmit={handleAddPath} className="flex gap-2">
                <select
                  value={newPathType}
                  onChange={(e: any) => setNewPathType(e.target.value)}
                  className="px-2 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-bold text-slate-900 dark:text-white"
                >
                  <option value="disallow">Disallow</option>
                  <option value="allow">Allow</option>
                </select>
                <input
                  type="text"
                  value={newPath}
                  onChange={(e) => setNewPath(e.target.value)}
                  placeholder="/folder/ or *.pdf"
                  className="flex-1 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs text-slate-900 dark:text-white font-mono focus:ring-1 focus:ring-indigo-500 outline-none"
                />
                <button
                  type="submit"
                  className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center gap-1 cursor-pointer"
                >
                  <Plus size={14} /> Add
                </button>
              </form>
            </div>
          </div>
        </div>

        {/* Right Output */}
        <div className="lg:col-span-6 flex flex-col min-h-[480px] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl overflow-hidden shadow-xs">
          <div className="px-5 py-3 bg-slate-50/80 dark:bg-slate-850 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-700 dark:text-slate-300 font-mono">
              robots.txt
            </span>
            <button
              onClick={handleCopy}
              className="px-3 py-1 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer"
            >
              {copied ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
          </div>

          <div className="p-6 flex-1 overflow-auto bg-white dark:bg-slate-900 font-mono text-xs sm:text-sm leading-relaxed text-slate-800 dark:text-slate-200 whitespace-pre-wrap select-all">
            {robotsTxt}
          </div>
        </div>
      </div>
    </div>
  );
}
